version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: aya
      POSTGRES_PASSWORD: aya123
      POSTGRES_DB: sales_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  etl:
    build: ./etl
    container_name: etl_pipeline
    depends_on:
      - postgres
    volumes:
      - ./data:/app/data

volumes:
  postgres_data:
